source 'https://rubygems.org'

gem 'rake',      "~> 10.3"
gem 'gorillib',  "~> 0.6"
gem 'pry',       "~> 0.10"

gem 'multi_json', ">= 1.1"

group :docker do
  gem 'childprocess'
  gem 'docker-api', :require => 'docker'
end
